# Generated by Django 5.0.14 on 2026-03-18 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("notification_type", models.CharField(max_length=50)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "fcm_response_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
