// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx57DjS8tt7v3d24aFYTpKHVoUiKLgSgE',
    appId: '1:265582480726:android:6a6de5f571a8874960daf7',
    messagingSenderId: '265582480726',
    projectId: 'manachyna-kusa-v2-2025',
    storageBucket: 'manachyna-kusa-v2-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMobU3aLeFTLtef9WEg6IEaOcCO9oQ0Vs',
    appId: '1:265582480726:ios:37a30dfd051ab60560daf7',
    messagingSenderId: '265582480726',
    projectId: 'manachyna-kusa-v2-2025',
    storageBucket: 'manachyna-kusa-v2-2025.firebasestorage.app',
    androidClientId: '265582480726-ahiesironihk30mkn6nljl9i6o89vdh9.apps.googleusercontent.com',
    iosClientId: '265582480726-mlmcq2vbm3mf2nnime4uj32tuhhvg22c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationManachynaKusa20',
  );
}
