# Generated by Django 5.0.14 on 2026-03-18 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("audio", "Audio"),
                            ("image", "Imagen"),
                            ("location", "Ubicación"),
                        ],
                        default="text",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="chat/audio/"),
                ),
                (
                    "image_file",
                    models.ImageField(blank=True, null=True, upload_to="chat/images/"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=12, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=12, null=True
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
